# repo-a/mkdocs.yml
INHERIT: docs/_core/core.mkdocs.yml

site_name: Singular Genomics Docs

site_url: https://docs.singulargenomics.com
site_description: Singular Genomics G4X documentation
repo_name: singular-genomics.github.io
repo_url: https://github.com/Singular-Genomics/singular-genomics.github.io

nav:
  - Docs Home: index.md
  
  - G4X-helpers:
      - https://docs.singulargenomics.com/G4X-helpers/
  
  - G4X-viewer:
      - https://docs.singulargenomics.com/G4X-viewer/

  - G4X-data:
      - g4x_data/index.md
      - Directory structure: g4x_data/output_structure.md
      - File reference:
        - g4x_data/output_files/index.md
        - root directory: g4x_data/output_files/root_directory.md
        - g4x_viewer: g4x_data/output_files/g4x_viewer.md
        - h_and_e: g4x_data/output_files/h_and_e.md
        - metrics: g4x_data/output_files/metrics.md
        - protein: g4x_data/output_files/protein.md
        - rna: g4x_data/output_files/rna.md
        - segmentation: g4x_data/output_files/segmentation.md
        - single_cell_data: g4x_data/output_files/single_cell_data.md
        - diagnostics: g4x_data/output_files/diagnostics.md
      
      - Data import: g4x_data/data_import.md

  - G4X-tutorials:
      - ./g4x_tutorials/index.md
      - Plot spatial: g4x_tutorials/plot_spatial.md
      - Segment data: g4x_tutorials/segment_data.md

#   - Changelog: changelog.md
