# repo-a/mkdocs.yml
INHERIT: docs/_core/core.mkdocs.yml

site_name: Singular Genomics Docs

site_url: https://docs.singulargenomics.com
site_description: Singular Genomics G4X documentation
repo_name: singular-genomics.github.io
repo_url: https://github.com/Singular-Genomics/singular-genomics.github.io

theme:
  features:
    - navigation.tabs

nav:
  - Docs Home: index.md
  
  - G4X-helpers:
      - https://docs.singulargenomics.com/G4X-helpers/
  
  - G4X-viewer:
      - https://docs.singulargenomics.com/G4X-viewer/

  - G4X-data:
      - g4x_data/index.md
      - G4X-output: g4x_data/g4x_output.md
      - data import: g4x_data/data_import.md

  - G4X-tutorials:
      - Introduction: g4x_tutorials/index.md
      - plot spatial: g4x_tutorials/plot_spatial.md
      - segment data: g4x_tutorials/segment_data.md

  - Changelog: changelog.md